name: flutter_todo
description: Todo - Mobile Tech Challenge

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #internationalization
  flutter_localizations:
    sdk: flutter

  #state management
  flutter_bloc: ^2.1.1

  #local database
  moor_flutter: ^2.0.0
  shared_preferences: ^0.5.4+8

  #di
  injector: ^1.0.8

  #ui
  cupertino_icons: ^0.1.2
  shimmer: ^1.0.1
  pull_to_refresh: ^1.5.7
  font_awesome_flutter: ^8.5.0

  #utils
  equatable: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: ^2.1.1


flutter:

  uses-material-design: true

  assets:
    - language/en.json
    - language/vi.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
